SEK-36 Добавить ещё одно WEB API (кроме Canvas, Fetch)
krovorgen/sekta pull request #24
Opened 2023-10-31 12:53 UTC by AndreevDA97

Добавлено звуковое сопровождение в игре (звук на фоне, бег и прыжки игрока).

2023-10-31 14:47 UTC, LevVPaname approved these changes

2023-11-01 13:31 UTC, IvanPeleshok requested changes
Проделана большая работа!
Здорово потрудились!

Есть вопрос и небольшое замечание к работе
Хотелось бы получить ответ на вопрос

В остальном всё гуд

Хорошего дня :)

2023-11-01 13:31 UTC, IvanPeleshok commented on packages/client/src/pages/Game/Game.tsx
> -      gameEngine?.destroy()
Точно нет необходимости уничтожать игру при вызове хука?

2023-11-01 13:31 UTC, IvanPeleshok commented on packages/client/src/game/core/utils/Sound.ts
> +    this._sound.volume = props.volume ?? 1.0
1.0 - лучше в константу вынести

2023-11-01 22:40 UTC, AndreevDA97 commented on packages/client/src/pages/Game/Game.tsx
> -      gameEngine?.destroy()
Проработал вопрос, вернул высвобождение ресурсов при размонтировании.

2023-11-01 22:41 UTC, AndreevDA97 commented on packages/client/src/game/core/utils/Sound.ts
> +    this._sound.volume = props.volume ?? 1.0
Вынес в константу общий уровень громкости.

2023-11-02 07:45 UTC, IvanPeleshok approved these changes
Отличная работа!
Поздравляю, апрув

Хорошего дня :)

2023-11-02 08:57 UTC, merged