Sek 38: Настроить Express для Server Side Rendering (без Redux, просто отдавать React-страничку)
krovorgen/sekta pull request #25
Opened 2023-11-01 06:55 UTC by krovorgen

SSR
<img width="737" alt="image" src="https://github.com/krovorgen/sekta/assets/72916714/31db69e4-2a1b-46df-a9f4-cb7d583d6a2e">

2023-11-01 08:49 UTC, AndreevDA97 approved these changes

2023-11-02 15:51 UTC, IvanPeleshok commented on packages/client/src/AppWithoutRedux.tsx
> +export const AppWithoutRedux = () => (
Подскажи, пожалуйста, почему моки компонентов?
Планируется добавить функциональные компоненты?

2023-11-02 15:53 UTC, IvanPeleshok requested changes
Проделана большая работа!
Здорово потрудились!

Есть небольшой вопрос относительно замоканных компонентов, но есть подозрение, что они будет заменены на этапе интеграции редакса

Как только получу положительный ответ - будет апрув :)

Хорошего дня 🚀

2023-11-02 16:28 UTC, krovorgen commented on packages/client/src/AppWithoutRedux.tsx
> +export const AppWithoutRedux = () => (
потому что все страницы обёрнуты хоком, внутри которого есть обращения к редаксу и всё ломается по итогу

2023-11-02 16:32 UTC, IvanPeleshok commented on packages/client/src/AppWithoutRedux.tsx
> +export const AppWithoutRedux = () => (
> потому что все страницы обёрнуты хоком, внутри которого есть обращения к редаксу и всё ломается по итогу

В дальнейшем собираетесь исправлять? (ответ очевиден, но все же спрошу :))

2023-11-02 16:51 UTC, krovorgen commented on packages/client/src/AppWithoutRedux.tsx
> +export const AppWithoutRedux = () => (
> > потому что все страницы обёрнуты хоком, внутри которого есть обращения к редаксу и всё ломается по итогу
> 
> В дальнейшем собираетесь исправлять? (ответ очевиден, но все же спрошу :))

конечно, ждёт уже следующий человек чтобы продолжить

2023-11-03 07:48 UTC, IvanPeleshok approved these changes
Замечательная работа!
Апрув

2023-11-03 09:25 UTC, merged