Sek 52 support forum api on client
krovorgen/sekta pull request #29
Opened 2023-11-09 11:14 UTC by Foxylabstory

### Какую задачу решаем
Подключить фронт форума к апи.

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2023-11-09 19:26 UTC, glow27 commented on packages/client/src/utils/consoleError.ts
> +    console.log(responseBody.reason)
тут можно console.error использовать `console.error(responseBody.reason)`

2023-11-09 19:29 UTC, glow27 commented on packages/client/src/api/ForumAPI.ts
> +}
у нас уже есть тип пользователя в packages/client/src/types/index.ts, мне кажется лучше его использовать и не дублировать, и вынести типы в отдельный файл еще можно

2023-11-09 19:30 UTC, glow27 commented on packages/client/index.html
> +  <script>window.initialState = null<!--store-data-->;</script>
а зачем тут null?

2023-11-09 19:32 UTC, glow27 approved these changes

2023-11-10 04:46 UTC, Foxylabstory commented on packages/client/src/utils/consoleError.ts
> +    console.log(responseBody.reason)
"+"

2023-11-10 04:50 UTC, Foxylabstory commented on packages/client/index.html
> +  <script>window.initialState = null<!--store-data-->;</script>
Затем, что присваивание было пустое, а "<!--store-data-->" для интерпретатора пустое место, ну я и подставил ничего, что бы ошибку убрать в консоли. Там Конечно еще дохрена красного, но потом я подумал, что эта ветка не для исправления ошибок, но эту трогать уже не стал.

2023-11-10 05:21 UTC, Foxylabstory commented on packages/client/src/api/ForumAPI.ts
> +}
Точно, я забыл про эту папку.
Все типы переехали туда.

2023-11-11 12:09 UTC, Olegas commented on packages/client/src/api/ForumAPI.ts
> +          'Access-Control-Allow-Origin': 'http://127.0.0.1:3000',
Для чего при запросе задавать этот заголовок? Выглядит лишним. Ведь этот заголовок обычно [используется в ответе](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin) а не в запросе.

2023-11-11 12:11 UTC, Olegas commented on packages/client/src/pages/Forum/Forum.tsx
> +        // created_at: Math.floor(Math.random() * 1000).toString(),
Не надо оставлять в проекте закомментированный код - это замусоривает кодовую базу.

2023-11-11 12:12 UTC, Olegas commented on packages/client/src/pages/Forum/ForumTopic/ForumTopic.tsx
> +      const arr = await ForumAPI.getTopics()
Очень спорное решение. Лучше сделать метод получения топика по id а не вытаскивать все-все-все и искать одно совпадение. Это лишняя нагрузка на бэкэнд и базу данных

2023-11-11 12:14 UTC, Olegas commented on packages/client/src/pages/Forum/components/table/ForumsTable.tsx
> +  const rows = useMemo(() => data, [data])
Такой useMemo не нужен. Зачем запоминать данные если при смене данных нужно будет заново перезапомнить? И при этом не делать никаких других манипуляций с ними. Можно просто data использовать без мемоизации.

2023-11-11 12:14 UTC, Olegas commented on packages/client/src/pages/Forum/components/table/ForumsTable.tsx
> +  }, [rows, page, perPage])
Для примера вот тут мемоизация имеет смысл - тут вычисляется производное состояние.

2023-11-11 12:15 UTC, Olegas commented on packages/client/src/utils/timeFormatter.ts
> +export const formatDate = (inputDate: string): string => {
Посмотри на функцию [toLocaleString](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleString), возможно она подойдет и можно перейти на стандартную функцию и не писать свою

2023-11-11 12:16 UTC, Olegas commented on packages/server/index.ts
> +// import { checkAuth } from './src/middlewares/checkAuth'
Почему убрана проверка авторизации? PR не должен ломать предыдущее состояние проекта а должен лишь улучшать его.

2023-11-11 12:17 UTC, Olegas requested changes
Добрый день.
Есть замечания по коду - написал их в комментариях.
Нужно доработать.

2023-11-11 23:49 UTC, glow27 commented on packages/client/index.html
> +  <script>window.initialState = null<!--store-data-->;</script>
я пофиксил эту ошибку, тут null нужно убрать, а то получается что мы зря начальный стейт с бэка присылаем

2023-11-12 09:38 UTC, Foxylabstory commented on packages/server/index.ts
> +// import { checkAuth } from './src/middlewares/checkAuth'
Потому, что с проверкой авторизации куки не долетают до сервера, закомментировано, что бы функциональность работала. В соседней ветке там вроде поправили, но определенной уверенности нет. В любом случае, задача не в рамках данной ветки.
Этот комментарий блокирующий?

2023-11-12 09:44 UTC, Foxylabstory commented on packages/client/src/utils/timeFormatter.ts
> +export const formatDate = (inputDate: string): string => {
"Аргументы locales и options поддерживаются ещё не всеми браузерами"
Нужно будет писать проверку, вместо того, что бы использовать простой и рабочий метод.
За полезную информацию спасибо. 
Комментарий является блокирующим? Или из раздела можно лучше?

2023-11-12 09:45 UTC, Foxylabstory commented on packages/client/src/pages/Forum/components/table/ForumsTable.tsx
> +  }, [rows, page, perPage])
Хорошо

2023-11-12 09:47 UTC, Foxylabstory commented on packages/client/src/pages/Forum/ForumTopic/ForumTopic.tsx
> +      const arr = await ForumAPI.getTopics()
Сервер не предоставил ручки для получения топика по его id, изначально рассчитывал на это, но его не оказалось. В виду этого поиск по всем топикам.
Комментарий блокирующий?

2023-11-12 09:47 UTC, Foxylabstory commented on packages/client/src/pages/Forum/Forum.tsx
> +        // created_at: Math.floor(Math.random() * 1000).toString(),
Проглядел, уберу.

2023-11-12 09:48 UTC, Foxylabstory commented on packages/client/index.html
> +  <script>window.initialState = null<!--store-data-->;</script>
Оставляю как было?

2023-11-12 12:07 UTC, Olegas commented on packages/client/src/pages/Forum/ForumTopic/ForumTopic.tsx
> +      const arr = await ForumAPI.getTopics()
Ок, оставим пока как есть

2023-11-12 12:08 UTC, Olegas commented on packages/client/src/utils/timeFormatter.ts
> +export const formatDate = (inputDate: string): string => {
Не блокирует. Просто как совет.

2023-11-12 12:08 UTC, Olegas commented on packages/server/index.ts
> +// import { checkAuth } from './src/middlewares/checkAuth'
Ок, если чинят в другом месте - пока оставим в этой задаче так

2023-11-12 12:09 UTC, Foxylabstory commented on packages/client/src/pages/Forum/Forum.tsx
> +        // created_at: Math.floor(Math.random() * 1000).toString(),
готово

2023-11-12 12:14 UTC, Foxylabstory commented on packages/client/index.html
> +  <script>window.initialState = null<!--store-data-->;</script>
null стрер, но пустое присваивание выглядит конечно странно

2023-11-12 12:17 UTC, Foxylabstory commented on packages/client/src/api/ForumAPI.ts
> +          'Access-Control-Allow-Origin': 'http://127.0.0.1:3000',
Поправил

2023-11-12 12:19 UTC, Foxylabstory commented on packages/client/src/pages/Forum/components/table/ForumsTable.tsx
> +  const rows = useMemo(() => data, [data])
осталось от предыдущей версии, когда ручек не было и работал с фейковыми данными. Поправил

2023-11-12 12:31 UTC, Foxylabstory commented
> Добрый день. Есть замечания по коду - написал их в комментариях. Нужно доработать.

Правки внес.

2023-11-12 13:02 UTC, glow27 commented on packages/client/index.html
> +  <script>window.initialState = null<!--store-data-->;</script>
почему пустое, <!--store-data--> меняется на строку со стейтом, можешь посмотреть что в первом запросе html страницы приходит или в моем прошлом пр на скрине

2023-11-13 08:44 UTC, Olegas approved these changes
Работа принята

2023-11-13 08:46 UTC, Foxylabstory commented
> Работа принята

Спасибо. Всего доброго.

2023-11-13 08:46 UTC, merged