Feat/sek 12 main page
krovorgen/sekta pull request #7
Opened 2023-09-20 20:08 UTC by LevVPaname

### Какую задачу решаем

### Скриншоты/видяшка (если есть)
<img width="1440" alt="Снимок экрана 2023-09-20 в 23 07 57" src="https://github.com/krovorgen/sekta/assets/59284623/7ff48951-46b4-403f-891d-72299b552034">

### TBD (если есть)

2023-09-21 19:46 UTC, krovorgen approved these changes

2023-09-22 09:19 UTC, IvanPeleshok commented on packages/client/src/App.test.tsx
> +test.skip('Example test', async () => {
А для чего скипать тест?

2023-09-22 09:19 UTC, IvanPeleshok commented on packages/client/src/Layouts/Base/Layout.tsx
> +  }, [])
Предлагаю между блоками оставлять отступ в одну строку

2023-09-22 09:20 UTC, IvanPeleshok commented on packages/client/src/Layouts/Base/Layout.tsx
> +        <NavbarLink to="/settings">Профиль</NavbarLink>
Возможно есть смысл подумать о том, чтобы роуты вынести в переменную/паречисление

2023-09-22 09:22 UTC, IvanPeleshok commented on packages/client/src/Layouts/Base/navbar-link/NavbarLink.tsx
> +        isActive ? cn(styles.navbarlink, styles.active) : styles.navbarlink
Предлагаю использовать classNames в более удобной форме
```
({ isActive }) => cn(styles.navLink, {
  [styles.active]: isActive
})
```

2023-09-22 09:24 UTC, IvanPeleshok commented on packages/client/src/pages/Root/Root.tsx
> +          onClick={() => navigate(RoutePath.Game)}
Инлайн колбеки лучше не писать, т.к такое сложно будет рефакторить и оптимизировать в дальнейшем

Предлагаю выносить в отдельные методы до return JSX
Так же предлагаю ознакомиться с оптимизацией с помощью useCallback
https://react.dev/reference/react/useCallback

2023-09-22 09:26 UTC, IvanPeleshok commented on packages/client/src/Layouts/Base/navbar-link/NavbarLink.tsx
> +  children: string
В либе React есть дженерик тип, который внутри себя содержит интерфейс children
type PropsWithChildren<P> = P & { children?: ReactNode };

Предлагаю в дальнейшем использовать его
Пример использования: https://blog.logrocket.com/using-react-children-prop-with-typescript/#using-propswithchildren-type:~:text=You%20can%20go%20ahead%20and%20introduce%20the%20children%20prop%20as%20follows%3A

2023-09-22 09:26 UTC, IvanPeleshok commented on packages/client/src/router/index.tsx
> +  createRoutesFromElements(
Нраица)

2023-09-22 09:33 UTC, IvanPeleshok requested changes
Проделана огромная работа!
Всё нравится, но есть небольшие некритические замечания :)

Предлагаю ознакомиться и поправить то, что вам показалось действительно важным

После доработок (или их отсутствия) приму работу

2023-09-23 03:40 UTC, LevVPaname commented on packages/client/src/App.test.tsx
> +test.skip('Example test', async () => {
он вроде ломал сборку, а мы пока решили не вносить правки в тесты

2023-09-23 04:33 UTC, IvanPeleshok approved these changes
Всё замечательно, апрув :)

2023-09-23 07:04 UTC, merged